fieldLayouts:
  4678c0f9-f3dc-4ffd-b70d-2b88652ebb39:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 03529a05-cdd3-4622-b98f-796575037ef8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bde4c2bf-2d99-405d-8328-2a8a6d1a2622 # rich text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2794282-464e-4284-92ca-51b4ac93e993
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 00387e9f-b8bc-4db7-9b88-7f4b7dd81e78 # about me image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 754d6260-a07f-4210-8a3b-96fbf5a10d79
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 913583b2-c61d-4dac-a7f1-a6a980710247 # redactText
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: df976db3-4468-4697-a07f-990e0aa7983f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 19546b0a-ed17-4ee5-9b9f-af0e8e7e98d8
        userCondition: null
handle: aboutMe
hasTitleField: false
name: 'about me'
section: 049bab6c-69dc-48cb-86ed-93ff908e98ce # about me
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
