baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: website-catalogue-jenna
primary: true
siteGroup: 44b7e98b-b731-4515-bf97-08345b465c53 # website-catalogue-jenna
sortOrder: 1
