columnSuffix: null
contentColumnType: string
fieldGroup: fc9333db-6621-4d4f-ba22-77708c9499dc # Common
handle: bannerImage
instructions: null
name: 'banner image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:c0fd89aa-f100-43a6-8cd0-c8bd2cdcadbb' # clothing assets
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: thumbs
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:c0fd89aa-f100-43a6-8cd0-c8bd2cdcadbb' # clothing assets
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
      -
        - conditionRules
        -
          -
            __assoc__:
              -
                - class
                - craft\elements\conditions\assets\FileSizeConditionRule
              -
                - uid
                - bbc16d43-466a-4597-939d-ae0e8b678055
              -
                - operator
                - '<'
              -
                - value
                - '100'
              -
                - maxValue
                - ''
              -
                - unit
                - MB
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
