defaultPlacement: end
enableVersioning: true
handle: aboutMe
name: 'about me'
propagationMethod: all
siteSettings:
  6e810cb9-8c20-4755-a797-96bd6f846e03: # website-catalogue-jenna
    enabledByDefault: true
    hasUrls: true
    template: _about.twig
    uriFormat: about-me
type: single
