defaultPlacement: end
enableVersioning: true
handle: clothing
name: clothing
propagationMethod: all
siteSettings:
  6e810cb9-8c20-4755-a797-96bd6f846e03: # website-catalogue-jenna
    enabledByDefault: true
    hasUrls: true
    template: clothing/_entry
    uriFormat: 'clothing/{slug}'
type: channel
