defaultPlacement: end
enableVersioning: true
handle: footer
name: footer
propagationMethod: all
siteSettings:
  6e810cb9-8c20-4755-a797-96bd6f846e03: # website-catalogue-jenna
    enabledByDefault: true
    hasUrls: true
    template: footer/_entry
    uriFormat: footer
type: single
